# Generated by Django 4.2.5 on 2023-10-09 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_listing_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='buyPrice',
        ),
        migrations.AddField(
            model_name='listing',
            name='imageUrl',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='startingBid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startingBids', to='auctions.bids'),
        ),
        migrations.AddField(
            model_name='listing',
            name='listingCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auctions.category'),
        ),
    ]
