# Generated by Django 4.2.5 on 2023-10-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_comment_watchlist_remove_comments_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidUser',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bidAmount',
        ),
        migrations.AddField(
            model_name='bid',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
