# Generated by Django 4.2.5 on 2023-10-12 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_biduser_bid_user_remove_bid_bidamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidListings', to='auctions.listing'),
        ),
    ]
