# Generated by Django 4.2.5 on 2023-10-18 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_watchlist_listing_watchlist_listings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='listings', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listings',
            field=models.ManyToManyField(related_name='watchlist_items', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
